### ISSUE TITLE
在 Android 8.1 中只要一切換到其他 app 就會停止

### ISSUE THREAD

**Issue by maple3142** [yanggis/ChinaTunnel#140]
如題

logcat:

```logcat
FATAL EXCEPTION: main
Process: com.yanggis.chinatunnel, PID: 27643
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 actions=1 vis=PRIVATE)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1769)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by yanggis** [comment]
好的，谢谢反馈，但是现在没有8.1的系统做测试，可能很多问题没有发现

**Comment by yanggis** [comment]
试一下这个版本。
https://github.com/yanggis/ChinaTunnel/blob/master/chinatunnelVPN.1.5_for%20mibox3.apk
